mss: binary: add a check whenever swapfile exists
Signed-off-by: chickendrop89 <chickendrop89@gmail.com>

diff --git a/system/bin/magiskswap b/system/bin/magiskswap
--- a/system/bin/magiskswap
+++ b/system/bin/magiskswap
@@ -57,9 +57,12 @@ createSwapSpace(){
             # 1 Gigabyte = 1,048,576 Kilobytes
             COUNT_KB="$((COUNT * 1048576))";
 
-            cprint "swap-off and delete existing swapfile"
-            swapoff "$SWAPFILE"
-            rm -rf "$SWAPFILE" || abort "cannot remove swapfile!"
+            if [ -f "$SWAPFILE" ];
+                then
+                    cprint "swap-off and delete existing swapfile"
+                    swapoff "$SWAPFILE"
+                    rm -rf "$SWAPFILE" || abort "cannot remove swapfile!"
+            fi
 
             cprint "creating $COUNT GB swapfile"
             dd if=/dev/zero of="$SWAPFILE" bs=1024 count="$COUNT_KB" 1>/dev/null
